name: KiCad CI
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:9.0
      options: --user kicad
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Run ERC/DRC
      run: ci/validate.sh
