name: KiCad CI
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: kicad/kicad:9.0
      options: --user root
    steps:
    - name: Check out Code
      uses: actions/checkout@v4
    - name: Run ERC/DRC
      run: ci/validate.sh
    - name: Save ERC/DRC Reports
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: outputs/validation/*.json
        retention-days: 1
        overwrite: true
