name: KiCad CI
on: [push]
jobs:
  validate:
    runs-on: ubuntu-latest
    container: kicad/kicad:9.0
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        clean: false
        set-safe-directory: false
    - name: Run ERC/DRC
      run: ci/validate.sh
